#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities
{
	
	
	/// <summary>
	/// Select the key type to be retrieved from the keyvault
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum keytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Secret = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Certificate = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CertificateWithX5c = 2,
	}
	
	/// <summary>
	/// Select which application has the preauthorization to the keyvault
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum preauthorizedapplicationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDataverseFirstParty = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 1,
	}
	
	/// <summary>
	/// Status of the Key Vault Reference
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum keyvaultreference_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Key Vault Reference
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum keyvaultreference_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Contains data that refers to an Azure Key Vault containing credentials used to connect to secure web-hosted resources.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("keyvaultreference")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class KeyVaultReference : Microsoft.Xrm.Sdk.Entity
	{
		
				/// <summary>
		/// Available fields, a the time of codegen, for the keyvaultreference entity
		/// </summary>
		public partial class Fields
		{
			public const string ComponentIdUnique = "componentidunique";
			public const string ComponentState = "componentstate";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IsCustomizable = "iscustomizable";
			public const string IsManaged = "ismanaged";
			public const string IsValidated = "isvalidated";
			public const string KeyName = "keyname";
			public const string KeyType = "keytype";
			public const string KeyVaultReferenceId = "keyvaultreferenceid";
			public const string Id = "keyvaultreferenceid";
			public const string KeyVaultUri = "keyvaulturi";
			public const string ManagedIdentityId = "managedidentityid";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OverwriteTime = "overwritetime";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string PreAuthorizedApplicationType = "preauthorizedapplicationtype";
			public const string SolutionId = "solutionid";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string keyvaultreference_ManagedIdentity = "keyvaultreference_ManagedIdentity";
			public const string lk_keyvaultreference_createdby = "lk_keyvaultreference_createdby";
			public const string lk_keyvaultreference_createdonbehalfby = "lk_keyvaultreference_createdonbehalfby";
			public const string lk_keyvaultreference_modifiedby = "lk_keyvaultreference_modifiedby";
			public const string lk_keyvaultreference_modifiedonbehalfby = "lk_keyvaultreference_modifiedonbehalfby";
			public const string managedidentity_KeyVaultReference = "managedidentity_KeyVaultReference";
			public const string user_keyvaultreference = "user_keyvaultreference";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public KeyVaultReference() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "keyvaultreference";
		
		public const string EntityLogicalCollectionName = "keyvaultreferences";
		
		public const string EntitySetName = "keyvaultreferences";
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
		public System.Nullable<System.Guid> ComponentIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.SetAttributeValue("iscustomizable", value);
			}
		}
		
		/// <summary>
		/// Indicates whether the solution component is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isvalidated")]
		public System.Nullable<bool> IsValidated
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isvalidated");
			}
			set
			{
				this.SetAttributeValue("isvalidated", value);
			}
		}
		
		/// <summary>
		/// Name of the KeyVault Secret or Certificate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keyname")]
		public string KeyName
		{
			get
			{
				return this.GetAttributeValue<string>("keyname");
			}
			set
			{
				this.SetAttributeValue("keyname", value);
			}
		}
		
		/// <summary>
		/// The type of key to use.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keytype")]
		public virtual keytype? KeyType
		{
			get
			{
				return ((keytype?)(EntityOptionSetEnum.GetEnum(this, "keytype")));
			}
			set
			{
				this.SetAttributeValue("keytype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keyvaultreferenceid")]
		public System.Nullable<System.Guid> KeyVaultReferenceId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("keyvaultreferenceid");
			}
			set
			{
				this.SetAttributeValue("keyvaultreferenceid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keyvaultreferenceid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.KeyVaultReferenceId = value;
			}
		}
		
		/// <summary>
		/// The Uri for the Key Vault.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keyvaulturi")]
		public string KeyVaultUri
		{
			get
			{
				return this.GetAttributeValue<string>("keyvaulturi");
			}
			set
			{
				this.SetAttributeValue("keyvaulturi", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for managedidentity which if preauthorized for the keyvault.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("managedidentityid")]
		public Microsoft.Xrm.Sdk.EntityReference ManagedIdentityId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("managedidentityid");
			}
			set
			{
				this.SetAttributeValue("managedidentityid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// The type of pre-authorized application.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("preauthorizedapplicationtype")]
		public virtual preauthorizedapplicationtype? PreAuthorizedApplicationType
		{
			get
			{
				return ((preauthorizedapplicationtype?)(EntityOptionSetEnum.GetEnum(this, "preauthorizedapplicationtype")));
			}
			set
			{
				this.SetAttributeValue("preauthorizedapplicationtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Status of the Key Vault Reference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual keyvaultreference_statecode? statecode
		{
			get
			{
				return ((keyvaultreference_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Key Vault Reference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual keyvaultreference_statuscode? statuscode
		{
			get
			{
				return ((keyvaultreference_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N keyvaultreference_ManagedIdentity
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("keyvaultreference_ManagedIdentity")]
		public System.Collections.Generic.IEnumerable<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.ManagedIdentity> keyvaultreference_ManagedIdentity
		{
			get
			{
				return this.GetRelatedEntities<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.ManagedIdentity>("keyvaultreference_ManagedIdentity", null);
			}
			set
			{
				this.SetRelatedEntities<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.ManagedIdentity>("keyvaultreference_ManagedIdentity", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_keyvaultreference_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_keyvaultreference_createdby")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser lk_keyvaultreference_createdby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("lk_keyvaultreference_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_keyvaultreference_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_keyvaultreference_createdonbehalfby")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser lk_keyvaultreference_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("lk_keyvaultreference_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_keyvaultreference_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_keyvaultreference_modifiedby")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser lk_keyvaultreference_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("lk_keyvaultreference_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_keyvaultreference_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_keyvaultreference_modifiedonbehalfby")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser lk_keyvaultreference_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("lk_keyvaultreference_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 managedidentity_KeyVaultReference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("managedidentityid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("managedidentity_KeyVaultReference")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.ManagedIdentity managedidentity_KeyVaultReference
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.ManagedIdentity>("managedidentity_KeyVaultReference", null);
			}
			set
			{
				this.SetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.ManagedIdentity>("managedidentity_KeyVaultReference", null, value);
			}
		}
		
		/// <summary>
		/// N:1 user_keyvaultreference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_keyvaultreference")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser user_keyvaultreference
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("user_keyvaultreference", null);
			}
		}
	}
}
#pragma warning restore CS1591
