#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities
{
	
	
	/// <summary>
	/// Select a source to indicate where the credential should be fetched from - Client Secret or KeyVault or Is managed
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum credentialsource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ClientSecret = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KeyVault = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IsManaged = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftFirstPartyCertificate = 3,
	}
	
	/// <summary>
	/// Select Identity type for Managed Identity Record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum identitytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppRegisteration = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentId = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentIdentityBlueprint = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentUser = 3,
	}
	
	/// <summary>
	/// Status of the Managed Identity
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum managedidentity_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Managed Identity
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum managedidentity_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Select a scope to indicate the level of the subject name - Global Scope or Enviornment Scope or Dev Only Scope
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum subjectscope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GlobalScope = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnviornmentScope = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DevOnlyScope = 2,
	}
	
	/// <summary>
	/// Contains data to represent an Azure Active Directory Application used to connect to secure web-hosted resources.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("managedidentity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class ManagedIdentity : Microsoft.Xrm.Sdk.Entity
	{
		
				/// <summary>
		/// Available fields, a the time of codegen, for the managedidentity entity
		/// </summary>
		public partial class Fields
		{
			public const string ApplicationId = "applicationid";
			public const string ClientSecret = "clientsecret";
			public const string ComponentIdUnique = "componentidunique";
			public const string ComponentState = "componentstate";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CredentialSource = "credentialsource";
			public const string IdentityType = "identitytype";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IsCustomizable = "iscustomizable";
			public const string IsManaged = "ismanaged";
			public const string KeyVaultReferenceId = "keyvaultreferenceid";
			public const string ManagedIdentityId = "managedidentityid";
			public const string Id = "managedidentityid";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string Name = "name";
			public const string ObjectId = "objectid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OverwriteTime = "overwritetime";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ParentAgentBlueprintId = "parentagentblueprintid";
			public const string ParentAgentIdentityId = "parentagentidentityid";
			public const string SolutionId = "solutionid";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string SubjectScope = "subjectscope";
			public const string TenantId = "tenantid";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string Version = "version";
			public const string VersionNumber = "versionnumber";
			public const string managedidentity_KeyVaultReference = "managedidentity_KeyVaultReference";
			public const string managedidentity_PluginAssembly = "managedidentity_PluginAssembly";
			public const string managedidentity_pluginpackage = "managedidentity_pluginpackage";
			public const string keyvaultreference_ManagedIdentity = "keyvaultreference_ManagedIdentity";
			public const string lk_managedidentity_createdby = "lk_managedidentity_createdby";
			public const string lk_managedidentity_createdonbehalfby = "lk_managedidentity_createdonbehalfby";
			public const string lk_managedidentity_modifiedby = "lk_managedidentity_modifiedby";
			public const string lk_managedidentity_modifiedonbehalfby = "lk_managedidentity_modifiedonbehalfby";
			public const string user_managedidentity = "user_managedidentity";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public ManagedIdentity() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "managedidentity";
		
		public const string EntityLogicalCollectionName = "managedidentities";
		
		public const string EntitySetName = "managedidentities";
		
		/// <summary>
		/// Application Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("applicationid")]
		public System.Nullable<System.Guid> ApplicationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("applicationid");
			}
			set
			{
				this.SetAttributeValue("applicationid", value);
			}
		}
		
		/// <summary>
		/// Contains a secret for the Azure Active Directory application. Once set, it cannot be read except by Dataverse.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clientsecret")]
		public string ClientSecret
		{
			get
			{
				return this.GetAttributeValue<string>("clientsecret");
			}
			set
			{
				this.SetAttributeValue("clientsecret", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
		public System.Nullable<System.Guid> ComponentIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Where the Managed Identity will get the credentials to use.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("credentialsource")]
		public virtual credentialsource? CredentialSource
		{
			get
			{
				return ((credentialsource?)(EntityOptionSetEnum.GetEnum(this, "credentialsource")));
			}
			set
			{
				this.SetAttributeValue("credentialsource", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Determines Identity type for Managed Identity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("identitytype")]
		public virtual identitytype? IdentityType
		{
			get
			{
				return ((identitytype?)(EntityOptionSetEnum.GetEnum(this, "identitytype")));
			}
			set
			{
				this.SetAttributeValue("identitytype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.SetAttributeValue("iscustomizable", value);
			}
		}
		
		/// <summary>
		/// Indicates whether the solution component is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Unique identifier for keyvaultreference which contains the secret.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keyvaultreferenceid")]
		public Microsoft.Xrm.Sdk.EntityReference KeyVaultReferenceId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("keyvaultreferenceid");
			}
			set
			{
				this.SetAttributeValue("keyvaultreferenceid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("managedidentityid")]
		public System.Nullable<System.Guid> ManagedIdentityId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("managedidentityid");
			}
			set
			{
				this.SetAttributeValue("managedidentityid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("managedidentityid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ManagedIdentityId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// The name assigned to this Managed Identity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// ObjectId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		public System.Nullable<System.Guid> ObjectId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("objectid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// ParentAgentBlueprintId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentagentblueprintid")]
		public System.Nullable<System.Guid> ParentAgentBlueprintId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("parentagentblueprintid");
			}
			set
			{
				this.SetAttributeValue("parentagentblueprintid", value);
			}
		}
		
		/// <summary>
		/// ParentAgentIdentityId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentagentidentityid")]
		public System.Nullable<System.Guid> ParentAgentIdentityId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("parentagentidentityid");
			}
			set
			{
				this.SetAttributeValue("parentagentidentityid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Status of the Managed Identity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual managedidentity_statecode? statecode
		{
			get
			{
				return ((managedidentity_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Managed Identity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual managedidentity_statuscode? statuscode
		{
			get
			{
				return ((managedidentity_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Where the Scope of the SubjectName for Managed Identity will be determined.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectscope")]
		public virtual subjectscope? SubjectScope
		{
			get
			{
				return ((subjectscope?)(EntityOptionSetEnum.GetEnum(this, "subjectscope")));
			}
			set
			{
				this.SetAttributeValue("subjectscope", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// The Id of the Azure Active Directory Tenant that the Application is part of.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("tenantid")]
		public System.Nullable<System.Guid> TenantId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("tenantid");
			}
			set
			{
				this.SetAttributeValue("tenantid", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version indicating the format of the FIC subject.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("version")]
		public System.Nullable<int> Version
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("version");
			}
			set
			{
				this.SetAttributeValue("version", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N managedidentity_KeyVaultReference
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("managedidentity_KeyVaultReference")]
		public System.Collections.Generic.IEnumerable<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.KeyVaultReference> managedidentity_KeyVaultReference
		{
			get
			{
				return this.GetRelatedEntities<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.KeyVaultReference>("managedidentity_KeyVaultReference", null);
			}
			set
			{
				this.SetRelatedEntities<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.KeyVaultReference>("managedidentity_KeyVaultReference", null, value);
			}
		}
		
		/// <summary>
		/// 1:N managedidentity_PluginAssembly
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("managedidentity_PluginAssembly")]
		public System.Collections.Generic.IEnumerable<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.PluginAssembly> managedidentity_PluginAssembly
		{
			get
			{
				return this.GetRelatedEntities<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.PluginAssembly>("managedidentity_PluginAssembly", null);
			}
			set
			{
				this.SetRelatedEntities<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.PluginAssembly>("managedidentity_PluginAssembly", null, value);
			}
		}
		
		/// <summary>
		/// 1:N managedidentity_pluginpackage
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("managedidentity_pluginpackage")]
		public System.Collections.Generic.IEnumerable<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.PluginPackage> managedidentity_pluginpackage
		{
			get
			{
				return this.GetRelatedEntities<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.PluginPackage>("managedidentity_pluginpackage", null);
			}
			set
			{
				this.SetRelatedEntities<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.PluginPackage>("managedidentity_pluginpackage", null, value);
			}
		}
		
		/// <summary>
		/// N:1 keyvaultreference_ManagedIdentity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keyvaultreferenceid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("keyvaultreference_ManagedIdentity")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.KeyVaultReference keyvaultreference_ManagedIdentity
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.KeyVaultReference>("keyvaultreference_ManagedIdentity", null);
			}
			set
			{
				this.SetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.KeyVaultReference>("keyvaultreference_ManagedIdentity", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_managedidentity_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_managedidentity_createdby")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser lk_managedidentity_createdby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("lk_managedidentity_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_managedidentity_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_managedidentity_createdonbehalfby")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser lk_managedidentity_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("lk_managedidentity_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_managedidentity_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_managedidentity_modifiedby")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser lk_managedidentity_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("lk_managedidentity_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_managedidentity_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_managedidentity_modifiedonbehalfby")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser lk_managedidentity_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("lk_managedidentity_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_managedidentity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_managedidentity")]
		public FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser user_managedidentity
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformSdkExtensions.PluginRuntime.Entities.SystemUser>("user_managedidentity", null);
			}
		}
	}
}
#pragma warning restore CS1591
